name: 'Terraform GitHub Actions'
on:
  push:
    paths:
      - '*/**'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        id: init
        run: |
           rm -rf .terraform
           terraform init 
      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@master
        id: plan
        run: |
          terraform plan 
      - name: Terraform Apply
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
